### ISSUE TITLE
Happy Path E2E

### ISSUE THREAD

**Issue by blinky3713** [f-o-a-m/plasma-demo#21]
Happy path e2e means
- [x] make deposit in root chain contract
- [x] include deposit in plasma chain to receive utxo
- [x] spend utxo to another user
- [x] have that user exit the utxo back onto the root chain
- [x] finalize the exit
- [x] prove that it worked somehow
